version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bugTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
    ports:
      - "5432:5432" 
    restart: always
    networks:
      - my-network

  api:
    build:
      context: ./bug-tracker-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

  web:
    build: "./bug-tracker"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
     - postgres
     - api 
    networks:
      - my-network

networks:
  my-network: